name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v6.0.0
        with:
          images: ghcr.io/acme/app

      - name: Build with Bake
        uses: docker/bake-action@v6
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file-tags }}
            ${{ steps.meta.outputs.bake-file-labels }}
          push: false
